 
has_one: ~
has_many: ~
belongs_to: 
  UseCase: 
    foreign_key: use_case_id
    and: 
      eq_deleted: false
      
  Actor: 
    foreign_key: actor_id
    and: 
      eq_deleted: false
  
delete: ~
destroy: ~
attributes: 
  actor_id: 
    type: String
    default: ~
  use_case_id: 
    type: String
    default: ~
    validates_uniqueness_of: 
      allow_blank: true
      scope: [actor_id]
      and:
        eq_deleted: false
        nil_actor_id: false
  comment: 
    type: String
    default: ~
