 
has_one: ~
has_many: 
  actors: 
    classify: Actor
    foreign_key: use_case_diagram_id
    and: 
      eq_deleted: false

  notes: 
    classify: Note 
    foreign_key: use_case_diagram_id
    and:
      eq_deleted: false
                  
  knownActors: 
    classify: Actor
    foreign_key: use_case_diagram_id
    and: 
      eq_deleted: false
      ne_code: Unknown

  useCases: 
    classify: UseCase
    foreign_key: use_case_diagram_id
    and: 
      eq_deleted: false
      
  knownUseCases: 
    classify: UseCase
    foreign_key: use_case_diagram_id
    and: 
      eq_deleted: false
      ne_code: Unknown

  ActorHas: 
    classify: ActorHas
    foreign_key: actor_id
    and: 
      eq_deleted: false
      
belongs_to: 
  Project: 
    and: 
      eq_deleted: false
    
#delete: 
#  - Actor: 
#      foreign_key: use_case_diagram_id
#      method: delete
#      and: 
#        eq_deleted: false
#  - UseCase: 
#      foreign_key: use_case_diagram_id
#      method: delete
#      and: 
#        eq_deleted: false
#  - Note: 
#      foreign_key: use_case_diagram_id
#      method: delete
#      and: 
#        eq_deleted: false
        
#destroy: 
#  - Actor: 
#      foreign_key: use_case_diagram_id
#      method: destroy
#      and: 
#        eq_deleted: false
#  - UseCase: 
#      foreign_key: use_case_diagram_id
#      method: destroy
#      and: 
#        eq_deleted: false
#  - Note: 
#      foreign_key: use_case_diagram_id
#      method: destroy
#      and: 
#        eq_deleted: false
        
attributes: 
  code: 
    type: String
    default: ~
#    validates_presence_of: ~
    validates_uniqueness_of:
      allow_blank: true
      and: 
        eq_deleted: false
    validates_format_of: 
      with: '^([a-zA-Z]{1}[a-zA-Z\w ]{1,29})$'
    
  name: 
    type: String
    default: ~
#    validates_presence_of: ~
    validates_uniqueness_of: 
      allow_blank: true
      and: 
        eq_deleted: false
    validates_format_of: 
      with: '^([\u4e00-\u9fa5\w]{1,30})$'
      
  comment: 
    type: String
    default: ~
    validates_length_of: 
      allow_blank: true
      minimum: 0
      maximum: 200
